controllers:
    resource: ../src/Controller/
    type: annotation
    # (the type: annotation option also applies to attributes...)
    
# index:
#     path: /
#     controller: App\Controller\TestController::index


    
